# Generated by Django 4.2.6 on 2024-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='tipo',
            new_name='tipo_plato',
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(default='Sin ingredientes'),
        ),
    ]
