# Generated by Django 4.2.6 on 2024-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0002_rename_tipo_receta_tipo_plato_receta_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(),
        ),
    ]
