# Generated by Django 4.2.6 on 2024-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0003_remove_receta_descripcion_alter_receta_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
