# Generated by Django 4.2.6 on 2024-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0004_receta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
