# Generated by Django 4.2.6 on 2024-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0005_alter_receta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tipoplato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tipoPlato/'),
        ),
    ]
