# Generated by Django 4.2.6 on 2024-11-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0006_remove_receta_descripcion_tipoplato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ingredientes/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
