# Generated by Django 4.2.6 on 2024-11-17 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0007_ingrediente_descripcion_ingrediente_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo_plato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appRecetario.tipoplato')),
            ],
        ),
    ]
