# Generated by Django 4.2.6 on 2024-11-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0008_inspiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', to='appRecetario.ingrediente'),
        ),
    ]
