# Generated by Django 4.2.6 on 2024-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0009_remove_receta_ingredientes_receta_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(to='appRecetario.ingrediente'),
        ),
    ]
