# Generated by Django 4.2.6 on 2024-12-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetario', '0011_receta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='proceso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
